<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from /Users/edsel/git/biz.jmaconsulting.owngroups/xml/schema/CRM/Owngroups/PreferenceGroup.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:d436fd14b66a18c9f82596db96fe0b2d)
 */

/**
 * Database access object for the PreferenceGroup entity.
 */
class CRM_Owngroups_DAO_PreferenceGroup extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_preference_group';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique PreferenceGroup ID
   *
   * @var int
   */
  public $id;

  /**
   * FK to Group
   *
   * @var int
   */
  public $group_id;

  /**
   * Is this group shown on preference page
   *
   * @var int
   */
  public $is_preference;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_preference_group';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   */
  public static function getEntityTitle() {
    return ts('Preference Groups');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'group_id', 'civicrm_group', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Owngroups_ExtensionUtil::ts('Unique PreferenceGroup ID'),
          'required' => TRUE,
          'where' => 'civicrm_preference_group.id',
          'table_name' => 'civicrm_preference_group',
          'entity' => 'PreferenceGroup',
          'bao' => 'CRM_Owngroups_DAO_PreferenceGroup',
          'localizable' => 0,
          'add' => NULL,
        ],
        'group_id' => [
          'name' => 'group_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Owngroups_ExtensionUtil::ts('FK to Group'),
          'where' => 'civicrm_preference_group.group_id',
          'table_name' => 'civicrm_preference_group',
          'entity' => 'PreferenceGroup',
          'bao' => 'CRM_Owngroups_DAO_PreferenceGroup',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Group',
          'add' => NULL,
        ],
        'is_preference' => [
          'name' => 'is_preference',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Owngroups_ExtensionUtil::ts('Is this group shown on preference page'),
          'where' => 'civicrm_preference_group.is_preference',
          'table_name' => 'civicrm_preference_group',
          'entity' => 'PreferenceGroup',
          'bao' => 'CRM_Owngroups_DAO_PreferenceGroup',
          'localizable' => 0,
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'preference_group', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'preference_group', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
